### ISSUE TITLE
Regarding scaling factor

### ISSUE THREAD

**Issue by sandeepshukla1112** [ashutoshsriv/VASP-Direct-to-Cartesian-Coordinate-Transform#1]
Hi Ashutosh,

I want to know about the scaling factor in the converted cartesian POSCAR file. If the scaling factor in my direct format POSCAR file is other than 1.0 then it will remain the same or something else in the converted cartesian POSCAR format? 

Best,
Sandeep

**Comment by ashutoshsriv** [comment]
It will take the scaling factor that is present in your POSCAR file, which you are converting to cartesian.
